// 渲染配置常量
export const RENDER_CONFIG = {
  // 布局配置
  SIDEBAR_WIDTH: 250,
  LEGEND_WIDTH: 200,
  MARGIN: 50,
  
  // 轨道配置
  MIN_TRACK_HEIGHT: 15,
  MAX_TRACK_HEIGHT: 30,
  TRACK_SPACING: 5,
  
  // 特征配置
  MIN_ANGLE_WIDTH: 0.005,
  MIN_GAP_ANGLE: 0.0005,
  MAX_GAP_ANGLE: 0.002,
  GAP_ANGLE_RATIO: 0.05,
  
  // 标签配置
  LABEL_RADIUS_OFFSET: 60,
  LABEL_ANGLE_WIDTH: 0.08,
  LABEL_FONT_SIZE: 11,
  
  // 网格配置
  GRID_CIRCLES: 5,
  GRID_RADIAL_LINES: 12,
  
  // 比例尺配置
  SCALE_RADIUS_OFFSET: 30,
  SCALE_LENGTH_RATIO: 0.1,
  SCALE_FONT_SIZE: 12,
  
  // 图例配置
  LEGEND_ITEM_HEIGHT: 25,
  LEGEND_MARGIN: 20,
  LEGEND_PADDING: 10,
  LEGEND_TITLE_FONT_SIZE: 14,
  LEGEND_ITEM_FONT_SIZE: 12,
  
  // GC 轨道配置
  GC_MAX_BAR_HEIGHT_RATIO: 0.8,
  GC_CONTENT_NORMALIZATION: 20,
  GC_CONTENT_MIDPOINT: 50,
  GC_SKEW_RANGE: 0.5,
};

// 颜色常量
export const COLORS = {
  BACKGROUND: 0xffffff,
  GRID: 0xe0e0e0,
  TRACK_BACKGROUND: 0xf5f5f5,
  TEXT: 0x333333,
  BORDER: 0x333333,
};
